import { JournalDetailItemProps, JournalItemData } from '@/types/journals'

export const MOCK_JOURNALS: JournalItemData[] = [
  {
    id: 1,
    symbol: 'AAPL',
    symbolName: 'Apple Inc.',
    emoji: '😊',
    emotionLabel: '자신감',
    emotionCount: 5,
    returnRate: 15.3,
    currentPrice: 180.75,
    buyPrice: 156.5,
    buyDate: '2024.01.15',
    quantity: 10,
  },
  {
    id: 2,
    symbol: 'TSLA',
    symbolName: 'Tesla',
    emoji: '😰',
    emotionLabel: '불안',
    emotionCount: 5,
    returnRate: -2.35,
    currentPrice: 720.5,
    buyPrice: 737.82,
    buyDate: '2024.02.20',
    quantity: 10,
  },
  {
    id: 3,
    symbol: 'NVDA',
    symbolName: 'NVIDIA',
    emoji: '🤑',
    emotionLabel: '욕심',
    emotionCount: 5,
    returnRate: 28.5,
    currentPrice: 465.32,
    buyPrice: 362.15,
    buyDate: '2023.12.01',
    quantity: 1,
  },
]
// Mock 데이터
export const MOCK_JOURNAL_DETAIL: JournalDetailItemProps = {
  id: 1,
  symbol: 'AAPL',
  symbolName: 'Apple Inc.',
  buyDate: '2024.01.15',
  buyPrice: 156.5,
  currentPrice: 180.75,
  totalQuantity: 10,
  returnRate: 15.3,
  profit: 2430,
  totalRecords: 5,
  emotionHistory: [
    {
      date: '2024.03.15',
      emotion: '😊',
      emotionLabel: '자신감',
      price: 180.75,
      memo: '실적 발표 후 주가 급등. 역시 애플은 믿고 보는 종목이다.',
    },
    {
      date: '2024.03.10',
      emotion: '🤔',
      emotionLabel: '고민',
      price: 176.5,
      memo: '약간의 조정이 있었지만 장기적으로는 상승할 것 같다.',
    },
    {
      date: '2024.03.05',
      emotion: '😊',
      emotionLabel: '자신감',
      price: 178.8,
      memo: '뉴스에서 긍정적인 전망 보도. 홀딩 유지.',
    },
    {
      date: '2024.02.28',
      emotion: '😰',
      emotionLabel: '불안',
      price: 172.3,
      memo: '갑자기 하락해서 당황스럽다. 일단 지켜보자.',
    },
    {
      date: '2024.02.20',
      emotion: '😊',
      emotionLabel: '자신감',
      price: 179.6,
      memo: '드디어 수익 전환! 기분 좋다.',
    },
  ],
}
