CREATE TABLE IF NOT EXISTS emotions (
    id SERIAL PRIMARY KEY,
    journal_id INT NOT NULL REFERENCES journals(id) ON DELETE CASCADE,
    emotion_id VARCHAR(10) NOT NULL,
    price DECIMAL(15,2) NOT NULL,
    quantity INTEGER NOT NULL,
    memo TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);